INSERT INTO authors (id, name, biography) VALUES
                                              (1,  'Robert C. Martin',    'Robert Cecil Martin, known as "Uncle Bob", is an American software engineer and author renowned for promoting clean code and SOLID principles.'),
                                              (2,  'Martin Fowler',       'British software developer and author, a pioneer in agile methods, refactoring, and enterprise application patterns.'),
                                              (3,  'Joshua Bloch',        'Former principal engineer at Sun Microsystems and Google, best known for writing "Effective Java", one of the most influential Java books.'),
                                              (4,  'Gang of Four',        'Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides — authors of the seminal Design Patterns book.'),
                                              (5,  'Donald Knuth',        'American computer scientist and Professor Emeritus at Stanford, known for "The Art of Computer Programming" series.'),
                                              (6,  'Andrew Hunt',         'Andrew Hunt and David Thomas co-authored "The Pragmatic Programmer", one of the best-selling programming books of all time.'),
                                              (7,  'Linus Torvalds',      'Creator of the Linux kernel and Git version-control system. Subject of several authoritative biographies.'),
                                              (8,  'Eric Evans',          'Software design expert and author of "Domain-Driven Design", which defined modern DDD vocabulary and patterns.'),
                                              (9,  'Brian Goetz',         'Principal Java Language Architect at Oracle and lead author of "Java Concurrency in Practice".'),
                                              (10, 'Bruce Eckel',         'American author and computer programmer who wrote "Thinking in Java" and "Thinking in C++", popular university textbooks.'),
                                              (11, 'Herbert Schildt',     'American author of numerous programming books covering Java, C, C++, and C#; widely used in university curricula.'),
                                              (12, 'James Gosling',       'Creator of the Java programming language and co-author of "The Java Programming Language".'),
                                              (13, 'Kathy Sierra',        'Author of the popular "Head First" series of technical books, known for their unique, engaging visual style.'),
                                              (14, 'Craig Walls',         'Spring Framework expert and author of "Spring in Action", the definitive guide to Spring development.'),
                                              (15, 'Rod Johnson',         'Creator of the Spring Framework and author of "Expert One-on-One J2EE Design and Development".'),
                                              (16, 'Cay Horstmann',       'Author of "Core Java" series and computer science professor, widely used in university Java courses.'),
                                              (17, 'Thomas Cormen',       'Professor at Dartmouth College and co-author of "Introduction to Algorithms" (CLRS), the gold-standard algorithms textbook.'),
                                              (18, 'Michael T. Goodrich', 'Professor at UC Irvine, co-author of "Data Structures and Algorithms in Java", popular in CS curricula.'),
                                              (19, 'Frederick Brooks',    'Computer architect and manager known for "The Mythical Man-Month", essays on software engineering.'),
                                              (20, 'Steve McConnell',     'Software engineer and author of "Code Complete", a comprehensive manual of software construction.');