<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="java.time.LocalDateTime" %>
<%@ page import="java.util.List" %>
<!DOCTYPE html>

<!-- HelpController.java -> help.jsp -->

<html>
<head>
    <title>Help Center</title>
</head>
<body style="font-family: sans-serif; padding: 20px;">

    <%
        // Controller se bheja gaya data nikal rahe hain
        String name = (String) request.getAttribute("name");
        Integer roll = (Integer) request.getAttribute("rollNo");
        LocalDateTime time = (LocalDateTime) request.getAttribute("time");
        List<Integer> marks = (List<Integer>) request.getAttribute("userMarks");
    %>

    <h1>Support & Help Center</h1>
    <hr>

    <h3>User Information:</h3>
    <p><b>Name:</b> <%= name %></p>
    <p><b>Roll Number:</b> <%= roll %></p>
    <p><b>Request Time:</b> <%= time %></p>

    <h3>Academic Record (Marks):</h3>
    <ul>
        <% if(marks != null) {
            for(Integer m : marks) { %>
                <li>Subject Score: <%= m %></li>
        <% } } %>
    </ul>

    <footer style="margin-top: 50px; color: gray;">
        Generated by ModelAndView Class in Spring MVC
    </footer>

</body>
</html>